#!/bin/bash

threads=30
dpath="$HOME/data/jul18/436"
rpath="$dpath/beam_scan"
prtdirc="../prtdirc/build/prtdirc"

waitForMe (){
    while : 
    do 
	activth=$(ps aux | grep "root.exe.*[p]rocData\|[p]rtdirc -[^m,^c]" | wc -l)
	#printf "\r$statusline [$activth] ---- [$(($(date +%s) - start_time)) s] "
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
	sleep .5
    done
}
start_time=$(date +%s)
statusline="reco "

mkdir -p ${rpath}
for f in $dpath/beam_436_*C.root; do
    spath=$rpath/${f##*/}
    mkdir -p $spath
    for theta in `LANG=en_us seq -0.015 0.001 0.015`; do
	for phi in `LANG=en_us seq -0.015 0.001 0.015`; do
	    echo $theta $phi
	    $prtdirc -s 2 -i $f -o $spath/b_r.$theta.$phi.root -f 0 -e 2000 -tr 0.5 -t1 $theta -t2 $phi -v 0 -b 1 >/dev/null 2> /dev/null &
	    waitForMe $threads
	done
    done
    waitForMe 1
    # fileid=$(ls ${respath}/reco_*[^r].root | head -n 1 | cut -d'_' -f 2)
    hadd -f ${spath}/map.root ${spath}/b_r*[^r].root
done

