#!/bin/bash

binpath=$HOME/dirc/prtdirc/build
threads=25

start_time=$(date +%s)
statusline="reco "
waitForMe (){
    while : 
    do 
	activth=$(ps aux | grep "root.exe.*[p]rocData\|[p]rtdirc -[^m,^c]" | wc -l)
	#printf "\r$statusline [$activth] ---- [$(($(date +%s) - start_time)) s] "
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
	sleep .5
    done
}

for study in 401; do
    respath=$HOME/data/jul18/${study}/${study}r/beamscan
    mkdir -p ${respath}
    for f in $HOME/data/jul18/${study}/beam_401_*C.root; do
	lut="${f/C.root/S_cs_avr.root}"
	lut="${lut/beam/lut_beam}"
	for theta in `LANG=en_us seq -0.02 0.002 0.02`; do
	    for phi in `LANG=en_us seq -0.02 0.002 0.02`; do
		${binpath}/prtdirc -s 2 -i $f -u $lut -o ${respath}/reco_${theta}_${phi}.root -f 0 -e 2000 -tr 0.5 -t1 ${theta} -t2 ${phi} -v 0 -b 1 >/dev/null 2> /dev/null &
		waitForMe $threads
	    done
	done
	waitForMe 1
	fileid=$(ls ${respath}/reco_*[^r].root | head -n 1 | cut -d'_' -f 2)
	hadd -f ${respath}/map_${fileid}.root ${respath}/reco_${fileid}_*[^r].root
	#rm  ${respath}/reco_*.root
    done
done

