#!/bin/bash

threads=30
dpath="$HOME/data/jul18/436"
rpath="$dpath/step_scan"
prtdirc="../prtdirc/build/prtdirc"

waitForMe (){
    while : 
    do 
	activth=$(ps aux | grep "root.exe.*[p]rocData\|[p]rtdirc -[^m,^c]" | wc -l)
	#printf "\r$statusline [$activth] ---- [$(($(date +%s) - start_time)) s] "
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
	sleep .5
    done
}

start_time=$(date +%s)

if [ ${1} == "0" ]; then
    
    mkdir -p $rpath/luts

    statusline="XY step scan "
    for i in `seq 14 0.2 18` ; do
	# for j in `seq 64 0.2 68` ; do
	for j in `seq 122 0.2 126` ; do
	    # lout=$rpath/luts/b_s.$i.$j.root
	    # # $prtdirc -o $lout \
	    # # 	     -h 1 -l 3 -p 7.00 -a 25.00 -phi 0.00 -gz 424.00 -gx 145.00 -gsx $j -gsy $i -z 10.00 -g 2018 -c 2018 -study 436 \
	    # # 	     -s 1 -z 0 -a 180 -phi 0 -x "opticalphoton" -p "3.18 eV" -e 2000000 -b 1 &
	    # cd $HOME/dirc/prtdirc/macro && root -q -b loadlib.C lutmean_cs.C"(\"$lout\")" &
	    # waitForMe $threads
	    
	    for file in $dpath/beam_436_*C.root ; do
	    	spath=$rpath/${file##*/}
	    	mkdir -p $spath
	    	echo $spath
	    	$prtdirc -s 2 -u $rpath/luts/b_s.$i.$j.cs_avr.root -i $file -o $spath/b_r.$i.$j.root -tr 0.5 -f 0 -e 2000 -v 0 -b 1 -t2 $i -t3 $j &
	    	waitForMe $threads
	    done	    
	    
	done
    done
    waitForMe "1"

    printf "\r$statusline [-] done [$(($(date +%s) - start_time)) s]         \n"
    cd -
fi

if [ ${1} == "1" ]; then
    statusline="Y step scan "
    for i in `seq 8 0.5 25` ; do
	../build/prtdirc -o b_l$i.root \
			 -p 7 -h 1 -l 3 -a 25 -gz 378 -gx 85 -gsx 67.5 -gsy ${i} -z 10 -g 2015 -c 2015 \
			 -s 1 -z 0 -a 180 -x "opticalphoton" -p "3.18 eV" -g 0 -e 5000000 -b 1 \
			 > l_b$i.log && \
	    root -q -b loadlib.C lutmean_cs.C"(\"b_l$i.root\")" && \
	    ../build/prtdirc -s 2 -u b_l${i}_cs_avr.root -i ${jpath}/beam_15177040631C.root -o b_r_${i}.root -tr 1.5 -f 0 -e 5000 -v 1 -b 1 -t3 $i > /dev/null 2> /dev/null &
	waitForMe $threads
    done
    waitForMe "1"

    hadd -f r_step_scan.root b_r_*.root
    printf "\r$statusline [-] done [$(($(date +%s) - start_time)) s]         \n"
fi

if [ ${1} == "2" ]; then
    statusline="Divergence scan "
    for i in `seq -0.025 0.0005 0.025` ; do
	for j in `seq  -0.025 0.0005 0.025` ; do
	    ../build/prtdirc -s 2 -u ${jpath}/lut_beam_15177135523S10M_cs_avr.root -i ${jpath}/beam_15177135523C.root -o b_r_${i}_${j}.root -t1 1.5 -f -1 -e 2000 -v 0 -t2 ${i} -t3 ${j} -b 1  > /dev/null 2> /dev/null &
	    waitForMe $threads
	done
    done
    waitForMe "1"
    printf "\r$statusline [-] done [$(($(date +%s) - start_time)) s]         \n"
    sleep 2
    hadd -f r_sscan.root b_r_*.root
fi


