#!/bin/bash

binpath=~/dirc/prtdirc/build
threads=50

start_time=$(date +%s)
statusline="reco "
waitForMe (){
    while : 
    do 
	activth=$(ps aux | grep "root.exe.*[p]rocData\|[p]rtdirc -[^m,^c]" | wc -l)
	#printf "\r$statusline [$activth] ---- [$(($(date +%s) - start_time)) s] "
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
	sleep .5
    done
}

for study in 406; do
    aa=0    
    respath=/d/proc/jul18/${study}/beamscanC
    mkdir -p $respath
    for f in /d/proc/jul18/${study}/beam_*C.root; do
	lut="${f/C.root/S_cs_avr.root}"
	lut="${lut/beam/lut_beam}"
	for theta in `LANG=en_us seq -0.02 0.001 0.02`; do
	    for phi in `LANG=en_us seq -0.02 0.001 0.02`; do
		${binpath}/prtdirc -s 2 -i $f -u $lut -o ${respath}/reco_${theta}_${phi}.root -f 0 -e 1000 -tr 1.5 -t1 ${theta} -t2 ${phi} -v 0 -b 1 >/dev/null 2> /dev/null &
		waitForMe $threads
	    done
	done
	hadd -f $respath/map_$((aa++)).root $respath/reco*.root
    done
done

