#!/bin/bash

binpath=~/dirc/prtdirc/build
respath=~/dirc/prttools/tdata
threads=30

waitForMe (){
    while : 
    do 
	activth=$(ps aux | grep "root.exe.*[p]rocData\|[p]rtdirc " | wc -l)
	printf "\r$statusline [$activth] ---- [$(($(date +%s) - start_time)) s] "
	sleep .1
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
    done
}
for theta in `LANG=en_us seq -0.02 0.002 0.02`; do
    for phi in `LANG=en_us seq -0.01 0.0005 0.01`; do
	${binpath}/prtdirc -s 2 -i /d/proc/aug17/332/beam_s332_20C.root -u /d/proc/aug17/332/lut_beam_s332_25S10M_cs_avr.root -o ${respath}/reco_${theta}_${phi}.root -f 0 -e 1000 -tr 2.0 -t1 $theta -t2 $phi -v 0 -b 1 &
	waitForMe $threads
    done
done
hadd -f $respath/rt.root $respath/reco*.root 

