#!/bin/bash

iter=$1
opts=$2
fileid=$3
chisq=$4

echo "Iteratiion # $iter  with $opts"

rm b_*[root,log] 

rpath=$HOME/dirc/prtdirc/build
wpath=$HOME/dirc/prttools/fitgeom

cd  $rpath
for i in {1..32}; do
    ./prtdirc -o $wpath/b_h$i.root $opts \
	      -z 10 -tr 0.25 -e 50 -x "mix" -b 1 -r $i > $wpath/b_l$i.log &
done

sleep 1
  
while : 
do
    activth=$(ps aux | grep "[p]rt" | grep "b_h" | wc -l)
    diffth=$(($maxnthr-$activth))
    echo "We have $activth active prt simulations " 
    if [ "$activth" -eq 0 ]; then 
      break  
    fi
    sleep 1
done

sleep 1

cd  $wpath
hadd -f hits_${iter}.root b_h*.root

status=1
res="$status $iter $opts $chisq"
sed '1s/.*/'"$res"'/' -i status.dat
echo "$res">>status_${fileid}.log 
