#!/bin/bash

waitForMe (){
    while : 
    do 
	activth=$(ps aux | grep "[e]icdirc" | grep "h_b" | wc -l)
	printf "\r$statusline [$activth] ---- [$(($(date +%s) - start_time)) s] "
	sleep .1
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
    done
}  
threads=${1:-4}

tseed=$(($(date +%s%N)/1000000-1393400000000))
mkdir -p hdata

for ((i=22;i<=140;i++)); do
	../build/prtdirc -r $tseed$i -o hdata/h_b$i.root -e 500 -s 0 -x "pi+" -p "10 GeV" -a $i -h 1 -c 0 -l 3  -b 1 &
	waitForMe $threads
done
waitForMe "1"
